### ISSUE TITLE
buffer overrun in pipeline_bspatch_process

### ISSUE THREAD

**Issue by xrmx** [libpull/libpull#72]
With a modern gcc 8.2.0 compilation fails because of:

```
src/core/pipeline/bspatch.c: In function ‘pipeline_bspatch_process’:
src/core/pipeline/bspatch.c:80:30: warning: array subscript 8 is above array bounds of ‘uint8_t[8]’ {aka ‘unsigned char[8]’} [-Warray-bounds]
                     newsize.c[j-16]= *bufp & 0x7F;
```

**Comment by xrmx** [comment]
Looks like this cannot happen, maybe gcc is confused by `if (j != (16+8)) {` at line 77 which is always false as the j won't ever be more than 23 per `for (j=0; j<24; j++) {` at line 68.

**Comment by xrmx** [comment]
This pleases gcc for me:

```
diff --git a/src/core/pipeline/bspatch.c b/src/core/pipeline/bspatch.c
index d6bc7a6..5414914 100644
--- a/src/core/pipeline/bspatch.c
+++ b/src/core/pipeline/bspatch.c
@@ -74,7 +74,7 @@ int pipeline_bspatch_process(pipeline_ctx_t* ctx, uint8_t* buf, int len) {
                     return -1;
                 }
             } else {
-                if (j != (16+8)) {
+                if (j != (16+7)) {
                     newsize.c[j-16] = *bufp;
                 } else {
                     newsize.c[j-16]= *bufp & 0x7F;
```

**Comment by AntonioLangiu** [comment]
Hi, thanks for the issue!

Actually that code is in the middle of a refactoring process since that bspatch function can be heavily simplified. I modified the original bspatch function to allows streaming the bytes of the patch, however I'm rewriting it from scratch to reduce memory footprint, complexity and thus possible bugs.

I will test your patch tomorrow and add gcc 8.2.0 in the Travis build matrix.
